name: Validate
on: [push, pull_request]
jobs:
  validate:
    name: validate
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node22 runtime
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: rm -rf node_modules && yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run TSC
        run: yarn build

      - name: Validate Tags
        run: yarn validate-tags
